#import sys
#sys.path.append('../enz')
import enz 

seq = 'MTIKEMPQPKTFGELKNLPLLNTDKPVQALMKIADELGEIFKFEAPGRVTRYLSSQRLIKE\
ACDESRFDKNLSQAWKFVRDFAGDGLVTSWTHEKNWKKAHNILLPSFSQQAMKGYHAMMVDIAVQLVQ\
KWERLNADEHIEVPEDMTRLTLDTIGLCGFNYRFNSFYRDQPHPFITSMVRALDEAMNKSQRANPDDP\
AYDENKRQFQEDIKVMNDLVDKIIADRKASGEQSDDLLTHMLNGKDPETGEPLDDENIRYQIITFLIA\
GHETTSGLLSFALYFLVKNPHVLQKAAEEAARVLVDPVPSYKQVKQLKYVGMVLNEALRLWPTAPAFS\
LYAKEDTVLGGEYPLEKGDELMVLIPQLHRDKTIWGDDVEEFRPERFENPSAIPQHAFKPFGNGQRAC\
IGQQFALHEATLVLGMMLKHFDFEDHTNYELDIKETLTLKPEGFVVKAKSKKIPLGGIPSPSTEQSAKKVRK'

def main():
    pdb = '../data/1jme.pdb'
    p = enz.protein(pdb, seq = seq, key_sites = [82,87,188,330])
    #v = enz.vina(pdb, key_sites = [82, 87,400])
    print(p.dock('CCCCCCCCCCCC=O'))
    print(p.docking_results)
    p.save_docking_results('tmp')
    #print(p.KEY_SITES_DICT)
    #print(p.dock('CCCCCC=O'))
    #p.mutate(75,'W')
    #p.refold()



if __name__ == '__main__':
    main()
